import { Provider } from "@/Components/ui/provider";
import type { Metadata } from "next";
import "../styles/globals.css";
import { Footer } from "@/Components/footerSection/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar" suppressHydrationWarning>
      <body dir="rtl">
        <Provider>
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
